version: '3'

services:

  web:
    image: nginx:latest
    ports:
        - "8000:80"
        - "9000:9000"
    working_dir: /var/www
    volumes:
        - ./api:/var/www
        - ./vhost.conf:/etc/nginx/conf.d/site.conf
    depends_on:
        - php
        
  php:
    image: php:7-fpm
    volumes:
        - ./api:/var/www